languge: generic

# whenever we run docker we need superuser permissions
sudo: required
# travis ci will automatically install docker into the running container 
services:
  - docker

# commands to run before the installation, since we wont be copying the image id manually we use the tag feature e.g. below
# docker build -t <docker account name>/<github repo name> -f <source of docker file/commands> .
before_install:
  - docker build -t jamesgayht/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true jamesgayht/docker-react npm run test

# travisci is configured by default to deploy application to certain hosting provides e.g. AWS or digitalocean - so by saying elasticbeanstalk we are telling travis to deploy automatically  
deploy:
  provider: elasticbeanstalk
  
  # depends on your elastic beanstalk link e.g. 
  # Dockerreact-env.eba-5vw8gfau.ap-northeast-1.elasticbeanstalk.com
  region: "ap-northeast-1"
  
  # name in elasticbeanstalk
  app: "docker-react"

  #get the name from elasticbeanstalk
  env: "Dockerreact-env"

  # travis will take all your files from github and zip them and copy to an S3 bucket in AWS (a form of hard drive running on AWS)
  bucket_name: "elasticbeanstalk-ap-northeast-1-048335957869"
  # initially should be same as your app name
  bucket_path: "docker-react"

  # configure the file so that only updates on the master branch get update to production
  on:
    branch: master
  
  # configured on travis.ci in settings
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_KEY"
